CREATE TABLE CLIENTE (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR2(100)
	CPF VARCHAR2(11)
	);
	
CREATE TABLE PRODUTO (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR2(100),
	PRECO_UNITARIO NUMERIC(20,2)
	);
	
CREATE TABLE PEDIDO (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
	DATA_PEDIDO TIMESTAMP,
	STATUS VARCHAR2(30),
	TOTAL NUMERIC(20,2)
	);
	
CREATE TABLE ITEM_PEDIDO (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
	PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
	QUANTIDADE INTEGER
	);
	
	
	
	